### ISSUE TITLE
Notes not loading

### ISSUE THREAD

**Issue by ransurf** [ppeetteerrs/obsidian-zola#12]
Hi there! For some reason, none of the notes in the repo are loading onto the website.

Link to Netlify: https://johnmavrickgarden.netlify.app/
Link to notes repo: https://github.com/ransurf/Obsidian-Zola

Any help would be appreciated :)

**Comment by ppeetteerrs** [comment]
Wow you have a lot of notes O.o You just have to rename `_index.md` to `home.md` and change your `LANDING_PAGE` to `home`. I have recently added the gotcha in the `README.md`.

**Comment by ransurf** [comment]
I think I did the following changes, but it still seems to not load. Does it maybe have to do with the amount of notes I have?

**Comment by ppeetteerrs** [comment]
It should work now in the newest release. You can turn off `HOME_GRAPH` and turn on `PAGE_GRAPH` and `LOCAL_GRAPH` to make rendering time more bearable.
