### ISSUE TITLE
Only publish selective folders or files

### ISSUE THREAD

**Issue by NavSrijan** [ppeetteerrs/obsidian-zola#13]
Is there an option to hide or just show selective notes on the website. I don't want to publish my whole repo. If anyone can help, please do.

**Comment by ppeetteerrs** [comment]
When you create the GitHub repo, just use .gitignore to exclude things that you want to keep private! I keep my daily notes private :)

(I know this tool is targeted towards a non-technical audience but please forgive me for assuming familiarity with `git` as a programmer 😅)

**Comment by allenwoods** [comment]
Another way to support only publishing selective folders is to use a subtree branch, such as `gh-pages`. Set the repo as private and point the deploy branch to `gh-pages` in netlify.com, and a lot of workflows that support published in github-page can be reused.
