### ISSUE TITLE
My builds keep failling

### ISSUE THREAD

**Issue by SyedUmairCodes** [ppeetteerrs/obsidian-zola#14]
I updated a bunch of files and now I'm having errors when deploying on netlify. [This is my repo](https://github.com/SyedUmairCodes/obsidian-pkm)
![Screenshot_20220416_000729](https://user-images.githubusercontent.com/57952190/163622963-0570f3ed-31fb-47ab-87d2-63ad4f1425c8.png)

**Comment by ppeetteerrs** [comment]
I think I have replied you on Reddit! Please let me know if there are further issues :)
