### ISSUE TITLE
How do I properly update?

### ISSUE THREAD

**Issue by teateatea** [ppeetteerrs/obsidian-zola#15]
Hello! 

First off, thank you for all the work that you've done! It's really great stuff!

I think I've made some mistake to keep up to date with you, but my site no longer recognizes any pages/notes. 

Here's my [github repository](https://github.com/teateatea/heartbreaker), and [here's my netlify site](https://teakettle.netlify.app/docs/home)

- I've taken all my notes out except the 'home' note.
- I've copied from netlify.example.toml into my netlify.toml, and I've only changed the SITE_URL and REPO_URL to mine.
- Netlify says the deploy was successful (I've attached the log in case that'll help you),
- But 'home' can't be found, nor searched.

I'm not really sure what else to try, but I'd really appreciate the help.

Thanks again!!

[Netlify Deploy log - Tea Kettle 2022-04-16.txt](https://github.com/ppeetteerrs/obsidian-zola/files/8500797/Netlify.Deploy.log.-.Tea.Kettle.2022-04-16.txt)

**Comment by ppeetteerrs** [comment]
Sorry it was on me! I have a small error in the `run.sh` when `STRICT_LINE_BREAK` is turned off.
