### ISSUE TITLE
Possibility to add privacy policy and legal notice

### ISSUE THREAD

**Issue by Ctrl-A-Del** [ppeetteerrs/obsidian-zola#16]
In many countries in the EU, a website needs to have a legal notice and a privacy policy, especially if you are using Google Analytics. Would it be possible to add an easy way to add those sites via the toml file? 

I could imagine something where you define a variable where people can just copy and paste their policy etc. in HTML format. If this variable is set, there is a new site generated, that mainly consists out of this HTML code.

**Comment by ppeetteerrs** [comment]
Have you tried putting a privacy / legal notice HTML file in your Obsidian directory? The tool is able to copy the HTML files directly and display the corresponding page. E.g. If you have `privacy.html` in your Obsidian repo's root, then `<site>/docs/privacy.html` would point to that page.

**Comment by Ctrl-A-Del** [comment]
That basically works, thanks for the tip. But according to the law, these sites must be accessible from each page, usually via links in the footer. Maybe there could be some flag in the frontmatter of the note and if a note with this attribute is found, the according link is rendered. Unfortunately, I don't have the time right now, to try this myself.

**Comment by ppeetteerrs** [comment]
Sure, I would add a config field for additional footer content soon.

**Comment by ppeetteerrs** [comment]
Added in 79214eb99d3008be9389f5de2145e7bf8e1fa903
