### ISSUE TITLE
Adjust graph forces

### ISSUE THREAD

**Issue by MioJernstrom** [ppeetteerrs/obsidian-zola#20]
I wish there was a way to adjust the forces in the graph. Here is my global graph in Zola vs Obsidian. I'm not sure if there is a fix for this that I am missing or if my way of linking isn't ideal for Zolas graph view.

![image](https://user-images.githubusercontent.com/105303535/167708162-8ded6cde-d96e-4796-a5cf-173c38a663c4.png)
![image](https://user-images.githubusercontent.com/105303535/167707801-0efa8233-5008-4907-9ce5-fc5526c29c68.png)

**Comment by ppeetteerrs** [comment]
Added in 79214eb99d3008be9389f5de2145e7bf8e1fa903
