### ISSUE TITLE
I encountered error (exit code 2) during deployment

### ISSUE THREAD

**Issue by ZhipeiLiu** [ppeetteerrs/obsidian-zola#23]
5:58:58 PM: Building site...
5:58:58 PM: Failed to build the site
5:58:58 PM: Error: Error when parsing front matter of section `/opt/build/repo/__site/build/content/docs/inbox/_index.md`
5:58:58 PM: Reason: YAML deserialize error: Scan(ScanError { mark: Marker { index: 91, line: 7, col: 13 }, info: "unexpected character: `@'" })
5:58:58 PM: ​
5:58:58 PM: ────────────────────────────────────────────────────────────────
5:58:58 PM:   "build.command" failed                                        
5:58:58 PM: ────────────────────────────────────────────────────────────────
5:58:58 PM: ​
5:58:58 PM:   Error message
5:58:59 PM:   Command failed with exit code 1: rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh (https://ntl.fyi/exit-code-1)
5:58:59 PM: ​
5:58:59 PM:   Error location
5:58:59 PM:   In build.command from netlify.toml:
5:58:59 PM:   rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh
5:58:59 PM: ​
5:58:59 PM:   Resolved config
5:58:59 PM:   build:
5:58:59 PM:     command: rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh
5:58:59 PM:     commandOrigin: config
5:58:59 PM:     environment:
5:58:59 PM:       - LANDING_BUTTON
5:58:59 PM:       - LANDING_DESCRIPTION
5:58:59 PM:       - LANDING_PAGE
5:58:59 PM:       - LANDING_TITLE
5:58:59 PM:       - PYTHON_VERSION
5:58:59 PM:       - REPO_URL
5:58:59 PM:       - SITE_TITLE
5:58:59 PM:       - SITE_TITLE_TAB
5:58:59 PM:       - SITE_URL
5:58:59 PM:       - TIMEZONE
5:58:59 PM:       - ZOLA_VERSION
5:58:59 PM:       - SORT_BY
5:59:00 PM:       - GANALYTICS
5:59:00 PM:       - SLUGIFY
5:59:00 PM:       - HOME_GRAPH
5:59:00 PM:       - PAGE_GRAPH
5:59:00 PM:       - SIDEBAR_COLLAPSED
5:59:00 PM:     publish: /opt/build/repo/public
5:59:00 PM:     publishOrigin: config
5:59:00 PM: Caching artifacts
5:59:00 PM: Started saving build plugins
5:59:00 PM: Finished saving build plugins
5:59:00 PM: Started saving pip cache
5:59:00 PM: Finished saving pip cache
5:59:00 PM: Started saving emacs cask dependencies
5:59:00 PM: Finished saving emacs cask dependencies
5:59:00 PM: Started saving maven dependencies
5:59:00 PM: Finished saving maven dependencies
5:59:00 PM: Started saving boot dependencies
5:59:00 PM: Finished saving boot dependencies
5:59:00 PM: Started saving rust rustup cache
5:59:00 PM: Finished saving rust rustup cache
5:59:00 PM: Started saving go dependencies
5:59:00 PM: Finished saving go dependencies
5:59:00 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
5:59:01 PM: Failing build: Failed to build site
5:59:01 PM: Finished processing build request in 2m51.107181795s

My config file is attached:
![image](https://user-images.githubusercontent.com/25544152/170468833-cea62bad-391d-471e-95f9-937fecd400e3.png)

**Comment by ppeetteerrs** [comment]
Sorry for the late response. It seems like you have removed your notes repository, if you still encounter the issue please let me know again!
