### ISSUE TITLE
[Feature Request]Exclude folder/file from being published.

### ISSUE THREAD

**Issue by pgyogesh** [ppeetteerrs/obsidian-zola#24]
I would really like to have the option to exclude the file or folders from being published. I know, I can add it in `.gitignore` in my local repo.

But having the option to push to GH and exclude it from the website will be good.

**Comment by pgyogesh** [comment]
Found the workaround:
- Adding `rm -rf <directory-name> &&` in `command` worked.

**Comment by trwbox** [comment]
obsidian-export has support for a file called .export-ignore with the same syntax as .gitignore file, so you could also try creating that file, and seeing if it works

**Comment by ppeetteerrs** [comment]
Closing unless `.export-ignore` does not work
