### ISSUE TITLE
Website page not found

### ISSUE THREAD

**Issue by Yilunma1** [ppeetteerrs/obsidian-zola#27]
Hello,

I don't seem to understand why my website is looking like this and why it doesn't find my files.

I pasted netlify.toml in the vault file, in the root of the Git repo to be precise. Should I paste it where my landing page is ?

Thanks again for the awesome work !
![Capture d’écran (167)](https://user-images.githubusercontent.com/105647578/173160562-a9d39103-947e-464e-a90f-58f72f702161.png)

**Comment by ppeetteerrs** [comment]
Would you be able to provide your GitHub repo link?

**Comment by Yilunma1** [comment]
Yes sure : https://github.com/Yilunma1/Coffre_Agilbox

**Comment by ppeetteerrs** [comment]
Try adding `https://` to your `SITE_URL` in `netlify.toml`. Also, please change to `shape: "dot"` in `GRAPH_OPTIONS`. That would make things look better.
