### ISSUE TITLE
Incorrectly building internal links to headings

### ISSUE THREAD

**Issue by brandazzle** [ppeetteerrs/obsidian-zola#3]
On [my site built with this](https://github.com/brandazzle/movement-ontology/tree/master), links to headings e.g. `[[page#heading]]` get turned into links to `/page.md/#heading` rather than `/page/#heading`, resulting in broken links.

**Comment by ppeetteerrs** [comment]
Thanks for pointing that out. Issue should be resolved now, please retry and let me know if there are any issues!
