### ISSUE TITLE
[FEATURE REQUEST] Code blocks support

### ISSUE THREAD

**Issue by Yilunma1** [ppeetteerrs/obsidian-zola#35]
Will there be a support for code blocs ?

For example I want to show last modified date and time : 

```dataview
TABLE WITHOUT ID file.mtime AS "Dernière mise à jour"

WHERE file.path = this.file.path
```

**Comment by ppeetteerrs** [comment]
Do you mean syntax highlighting and code fences? It is already supported as part of the standard Markdown syntax. You can see [here](https://peteryuen.netlify.app/docs/programming/python/python/) for an example. If not, please kindly let me know what you mean by code blocks.

**Comment by Yilunma1** [comment]
Sorry, I mispoke, I was talking about the result of a query under code fences.

For example is it possible to show the result of the query (image 1), and not the query code itself, like in obsidian (image 2) ?

Thanks.

<img width="487" alt="Capture d’écran 2022-06-27 182537" src="https://user-images.githubusercontent.com/105647578/175990932-d585e9aa-5712-4914-80e1-31b04bf5c835.png">
<img width="444" alt="Capture d’écran 2022-06-27 183240" src="https://user-images.githubusercontent.com/105647578/175990956-38960190-a76b-4a16-86f9-216660bc0963.png">
