### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by internetautomat** [ppeetteerrs/obsidian-zola#4]
Hi! Should I create netlify.toml file before this step? And what should I change here? Should I change your vault link to mine in toml?

![image](https://user-images.githubusercontent.com/21055107/161632794-99251d74-2c01-47db-9042-5b2da67e7814.png)

**Comment by internetautomat** [comment]
Tried like this:
![image](https://user-images.githubusercontent.com/21055107/161632950-94ec8601-1f37-482b-862f-de265a1adbf3.png)

but getting error when deploy
![image](https://user-images.githubusercontent.com/21055107/161633181-ef27cb8b-0f29-4cca-aeb6-39a63d06d01a.png)

**Comment by ppeetteerrs** [comment]
Please note that you do not need to make changes to the `build.command` field in `netlify.toml`. You can compare your file with that from the example repo. Please let me know if there are further issues :)

**Comment by assopri** [comment]
Thank you! Followed this tip, however still having the following troble:

![image](https://user-images.githubusercontent.com/73235464/161696102-abb1fd57-fbbf-4434-802c-0e355b9129cd.png)

It might be smth with config file, however I didnt create it at all on my side.

![image](https://user-images.githubusercontent.com/73235464/161696322-f4c4593e-0c42-47b9-978e-bf546c217d30.png)

![image](https://user-images.githubusercontent.com/73235464/161696381-f6f97fd9-99c3-458c-bc44-a8541afdf9ee.png)

**Comment by ppeetteerrs** [comment]
You also need to set your `SITE_URL` in `netlify.toml` to your website's address.

**Comment by internetautomat** [comment]
Added and this worked!
![image](https://user-images.githubusercontent.com/21055107/161723416-ca9c0ff5-a92e-473d-84df-07dcd118b3d6.png)

**Comment by ppeetteerrs** [comment]
Great! I will close the issue then, have fun with your website!
