### ISSUE TITLE
SITE_URL not being set correctly

### ISSUE THREAD

**Issue by Svaught598** [ppeetteerrs/obsidian-zola#44]
I figured this out already, just recording here for posterity.

I was having an issue where the build was failing on netlify because the SITE_URL was set to `""` which for some reason was read in by the python script as `None`. I changed it to `" "` (string with a single space) and everything is now working as expected. Thanks for the awesome tool!

**Comment by ppeetteerrs** [comment]
Thanks for flagging this!
