### ISSUE TITLE
Website look is inproper

### ISSUE THREAD

**Issue by patrykpalej** [ppeetteerrs/obsidian-zola#46]
I followed the instruction in README file and deployed my website on netlify. For the beginning I cloned the repo with content from the author and used in as my own content which I pointed in netlify.toml. After the deploy my website has the following look. Did I do something wrong?

![netlify](https://user-images.githubusercontent.com/34798604/193341456-ba019b0b-1ce8-425f-b924-13d90cb96563.png)

**Comment by auspham** [comment]
have you specified the correct netlify url?

**Comment by keithsunhz** [comment]
I have the same issue

**Comment by ppeetteerrs** [comment]
Please kindly provide the link to your repository and a screenshot of the netlify error when creating an issue. However, as @rockmanvnx6 suggested, it is probably due to some errors in the config file.

**Comment by patrykpalej** [comment]
Thank for the answers. Incorrent netlify URL was the case.
