### ISSUE TITLE
New line characters miss, published from Windows Obsidian

### ISSUE THREAD

**Issue by assopri** [ppeetteerrs/obsidian-zola#5]
Can somehow fix that?
![image](https://user-images.githubusercontent.com/73235464/161724812-fdf282ac-f74f-4931-9db0-cb50dc53cc1f.png)

**Comment by assopri** [comment]
found it works just if there are 2 new line characters one by one

**Comment by ppeetteerrs** [comment]
Hi, I believe that standard Markdown ignores single line break. To get a consistent behaviour in Obsidian, you can turn on the `Strict line breaks` option.

![image](https://user-images.githubusercontent.com/8547778/161782154-d8c9df2b-94be-448b-90a3-862e2fa67a5e.png)

**Comment by assopri** [comment]
Thank you!
