### ISSUE TITLE
Can I hide particular element of UI?

### ISSUE THREAD

**Issue by assopri** [ppeetteerrs/obsidian-zola#6]
Can I hide particular element of UI, for instance my catalog (in my case its in any case useless, having all in one folder, I`m using MOCs (Maps Of Content) for making info hubs?
![image](https://user-images.githubusercontent.com/73235464/161820147-ce0b6f0d-f2fa-4dd0-a77a-3eef0b1fa204.png)

Also is there any possibility to show incoming links (files linking current file, like linked mentions in Obsidian)?

Thank you in advance!

**Comment by ppeetteerrs** [comment]
To hide the side bar:

1. Create a fork of this repo.
2. Change `templates/docs/page.html` to the following (basically removing `macros_sidebar::docs_sidebar` and changing the column widths.
3. Point your `netlify.toml` to your fork instead of my repo.

```html
{% extends "page.html" %}

{% block body %}
  {% set page_class = "docs single" %}
{% endblock body %}

{% block header %}
  {# This value is matched by the config.extra.menu.main~url #}
  {% set current_section = "docs" %}
  {{ macros_header::header(current_section=current_section)}}
{% endblock header %}

{% block content %}
<div class="wrap container" role="document">
  <div class="content">
    <div class="row flex-xl-nowrap">
	  {{ macros_toc::docs_toc(page=page) }}
      <main class="docs-content col-lg-16 col-xl-13">
        <h1>{{ page.title }}</h1>
        {% if page.extra.lead %}<p class="lead">{{ page.extra.lead | safe }}</p>{% endif %}
        {{ page.content | safe }}
        {% if config.extra.edit_page %}
          {{ macros_edit_page::docs_edit_page(current_path=current_path) }}
        {% endif %}
        {{ macros_navigation::docs_navigation(page=page, current_section=current_section) }}
      </main>
    </div>
  </div>
</div>
{% endblock content %}
```

**Comment by ppeetteerrs** [comment]
To reply to this:
> Also is there any possibility to show incoming links (files linking current file, like linked mentions in Obsidian)?

Currently this is not supported. My intention of this repository is to be a simple one-click solution to share Obsidian notes and I hope to keep it as minimalistic as possible. Please feel free to implement additional functionalities through forking. If you developed a feature that you think should be shared with everyone else a pull request is also welcomed! 🤤

**Comment by assopri** [comment]
Cool! Thank you for your help!

**Comment by assopri** [comment]
Btw, if I want to add Google Analytics code into the page, which template file you would suggest to add it to?

**Comment by ppeetteerrs** [comment]
Graph view can be used as a backlinking system now, clicking on connected nodes opens up the linked page. 7809c68ae5adca1be34f51f0a89f4e23e700d5f3
