### ISSUE TITLE
SITE_URL not being read

### ISSUE THREAD

**Issue by ndoniyor** [ppeetteerrs/obsidian-zola#65]
My deployment was working earlier, not sure what affected the sudden issue. Here is my netlify.toml (with GRAPH_OPTIONS omitted):

> 
> [build]
> 
> command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
> publish = "public"
> 
> [build.environment]
> \# (Optional) Text in landing page button
> LANDING_BUTTON = "Enter"
> \# (Optional) Site description on landing page
> LANDING_DESCRIPTION = ""
> \# (REQUIRED) The Markdown page linked to landing page button (e.g. put home for ./home.md)
> LANDING_PAGE = "home"
> \# (Optional) Site title on landing page
> LANDING_TITLE = "Spring 2023 Notes"
> PYTHON_VERSION = "3.8"
> \# (REQUIRED) Site repo URL
> REPO_URL = "https://github.com/ndoniyor/notes-spring-2023/"
> \# (Optional) Site title in navbar
> SITE_TITLE = ""
> \# (Optional) Site title in browser tab (leave blank to use SITE_TITLE)
> SITE_TITLE_TAB = ""
> \# (REQUIRED) Netlify site URL
> SITE_URL = "https://dnim-notes.netlify.app/"
> \# (Optional) Site Timezone
> TIMEZONE = "America/New_York"
> ZOLA_VERSION = "0.15.2"
> \# (Optional, default title) How to sort notes inside each section on the right sidebar ("date" or "title"). Subsections on side bar are sorted by title, the sort order cannot be changed.
> SORT_BY = "title"
> \# (Optional) Google Analytics Measurement ID
> GANALYTICS = ""
> \# (Optional, default true) Slugify URLs. Put "" to disable.
> SLUGIFY = "y"
> \# (Optional, default true) Shows knowledge graph on home page. Put "" to disable.
> HOME_GRAPH = "y"
> \# (Optional, default true) Shows knowledge graph on every page. Put "" to disable.
> PAGE_GRAPH = "y"
> \# (Optional, default false) Whether sidebar sections should be collapsed by default.
> SIDEBAR_COLLAPSED = ""
> \# (Optional, default blank) Additional footer content.
> FOOTER = ""
> \# (Optional, default main) Root section name.
> ROOT_SECTION_NAME = "main"

Netlify returns the following error:

> Build failed due to a user error: Build script returned non-zero exit code: 2

But when I run the build command on my own I get the following:

> `raise Exception(f"FATAL ERROR: build.environment.{key} not set!")
> Exception: FATAL ERROR: build.environment.SITE_URL not set!
> __site/run.sh: line 24: zola: command not found`

I dont understand why since SITE_URL is set.

**Comment by orditeck** [comment]
I think this morning Netlify changed something because we're all ultimately getting the same error:
`line 24: zola: command not found`

https://answers.netlify.com/t/error-127-when-deploying-a-zola-website/86029

Might also be related: https://answers.netlify.com/t/netlify-cannot-find-commands-like-rm-and-mkdir/86009

**Comment by orditeck** [comment]
It's confirmed that it was an issue on Netlify's side, it's fixed. It works now!

https://answers.netlify.com/t/jekyll-build-failing-today-exact-source-built-successfully-yesterday/86038/10?u=orditeck
