### ISSUE TITLE
Want to change cyrillic symbols to lat generating article name

### ISSUE THREAD

**Issue by assopri** [ppeetteerrs/obsidian-zola#7]
Hi! I forked repositary and want to change cyrillic symbols to lat generating article name. Which script is responcible for generating ther article URL?
![image](https://user-images.githubusercontent.com/73235464/162122377-f8500475-b330-471d-b42d-b76fc62e8485.png)

**Comment by assopri** [comment]
the similar feature already works here (when click on particular header): 
![image](https://user-images.githubusercontent.com/73235464/162124947-775f20c6-e3a3-4160-894f-c15d0b265470.png)

**Comment by ppeetteerrs** [comment]
HI, if you look into `run.sh`, you will see that `obsidian-export` is used to parse your Obsidian Markdown files. It handles all the link and URL generation according to the filenames. You can add a script before that step to convert your file names (and all associated links) but it might be easier to just set the filenames in Obsidian in lat and convert them to cyrillic in `convert.py`.

To convert filename in lat to article title in cyrillic, see `write_frontmatters` in `convert.py`, just change the way `title` is parsed.

As for why it works for heading links, see `filter_lines` in `convert.py`, I assume Python's string decoding handled that.

**Comment by assopri** [comment]
Thank you for the detailed responce!!

**Comment by assopri** [comment]
> HI, if you look into `run.sh`, you will see that `obsidian-export` is used to parse your Obsidian Markdown files. It handles all the link and URL generation according to the filenames. You can add a script before that step to convert your file names (and all associated links) but it might be easier to just set the filenames in Obsidian in lat and convert them to cyrillic in `convert.py`.
> 
> To convert filename in lat to article title in cyrillic, see `write_frontmatters` in `convert.py`, just change the way `title` is parsed.
> 
> As for why it works for heading links, see `filter_lines` in `convert.py`, I assume Python's string decoding handled that.

It`s a nice solution for cyrillic symbols, however I still face another issue = the spaces in filename are not replaced with dashes: https://peteryuen.netlify.app/docs/programming/python**%20**advanced**%20**typings/ . Can I somehow override the default URL generation mechanics of obsidian-export (to change spaces to dashes)?

**Comment by ppeetteerrs** [comment]
For that you can probably try turning on `slugify.paths` in `config.toml`. I think that is on Zola's part. I forgot why I disabled it, maybe it caused some bugs but you can try it haha.

**Comment by assopri** [comment]
Cool! Slugify paths solved both issue of spaces and cyrillyc to lat characters. If you remind what can go wrong with it - let me know)))
![image](https://user-images.githubusercontent.com/73235464/162556837-87ab213c-ac87-4e9d-a7ff-f374b98ec76d.png)

**Comment by assopri** [comment]
I found what happens. Even if slugify paths is on, urls in links still use default url generation format:
![image](https://user-images.githubusercontent.com/73235464/162556969-4f7c9b7c-19bb-4fae-a110-595f430e1233.png)

any ideas how can I fix that?

**Comment by ppeetteerrs** [comment]
You can probably just replace spaces with dashes in `replaced_links`. 

![Screenshot_20220409-155104_GitHub.png](https://user-images.githubusercontent.com/8547778/162562365-e99a3980-a698-4867-a207-6c4629ad1725.png)
