### ISSUE TITLE
Adding Google Analytics code

### ISSUE THREAD

**Issue by lofti198** [ppeetteerrs/obsidian-zola#8]
Hi! If I want to add Google Analytics code into the page, which template file you would suggest to add it to? (I already forked the solution).

**Comment by ppeetteerrs** [comment]
`templates/base.html` is probably the right place.

**Comment by ppeetteerrs** [comment]
Now this is a built-in configuration and there is no need to separately implement the functionality: 38497498a7b3590c01a5489ad20fed1ff8d7894a
