### ISSUE TITLE
Any way to turn on search dropdown for cyrillic search requests?

### ISSUE THREAD

**Issue by assopri** [ppeetteerrs/obsidian-zola#9]
Cyrillic search doesnt cause search result dropdown, thus I cannot choose and open search results. Any way to fix that?
![image](https://user-images.githubusercontent.com/73235464/162557021-17718f28-7525-459d-9c52-1514d8271c20.png)

**Comment by ppeetteerrs** [comment]
Searching is performed here. You can see if you can do any processing to the index and the query string in Javascript. Or whether changing the elasticsearch settings helps. 

![Screenshot_20220409-155603_GitHub.jpg](https://user-images.githubusercontent.com/8547778/162562494-bb0edaa1-74c4-4651-b513-a74acb0f4319.jpg)

**Comment by assopri** [comment]
Cool! I will try! Can I somehow setup debug/test environment on localhost or whatever not to commit-push forked zola sources and redeploy my netlify website each time I changed a piece of code?

**Comment by ppeetteerrs** [comment]
You can reference the build steps in `netlify.toml` and do it locally, just use `zola serve` to view the results instead.

**Comment by ppeetteerrs** [comment]
I will close the issue for now, hope it went smoothly 😺

**Comment by lofti198** [comment]
Thank you for your great help! Had a several difficulties to run it on Windows, mostly solved. Thank you!
